import { Campaign, AdGroup, Keyword } from '@/types/campaign';

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Brand Keywords',
    status: 'ENABLED',
    type: 'SEARCH',
    spend: 1234.56,
    clicks: 3420,
    impressions: 45000,
    conversions: 45,
    ctr: 7.6,
    cpa: 27.43,
    roas: 4.2,
    aiScore: 92,
    aiRecommendation: 'Strong performance. Consider increasing budget by 20%.',
  },
  {
    id: 'camp-2',
    name: 'Competitor Terms',
    status: 'ENABLED',
    type: 'SEARCH',
    spend: 2100.0,
    clicks: 1890,
    impressions: 32000,
    conversions: 12,
    ctr: 5.9,
    cpa: 175.0,
    roas: 0.8,
    aiScore: 34,
    aiRecommendation: 'High CPA detected. Review negative keywords and consider pausing low performers.',
  },
  {
    id: 'camp-3',
    name: 'PMax - All Products',
    status: 'ENABLED',
    type: 'PERFORMANCE_MAX',
    spend: 5600.0,
    clicks: 8900,
    impressions: 125000,
    conversions: 89,
    ctr: 7.12,
    cpa: 62.92,
    roas: 2.4,
    aiScore: 78,
    aiRecommendation: 'Good performance. Asset groups could benefit from more creative variety.',
  },
  {
    id: 'camp-4',
    name: 'Shopping Feed',
    status: 'ENABLED',
    type: 'SHOPPING',
    spend: 3200.0,
    clicks: 5600,
    impressions: 89000,
    conversions: 67,
    ctr: 6.29,
    cpa: 47.76,
    roas: 3.1,
    aiScore: 85,
    aiRecommendation: 'Excellent ROAS. Consider expanding product feed.',
  },
  {
    id: 'camp-5',
    name: 'Display Retargeting',
    status: 'PAUSED',
    type: 'DISPLAY',
    spend: 0,
    clicks: 0,
    impressions: 0,
    conversions: 0,
    ctr: 0,
    cpa: 0,
    roas: 0,
    aiScore: 0,
  },
  {
    id: 'camp-6',
    name: 'YouTube Brand Awareness',
    status: 'ENABLED',
    type: 'VIDEO',
    spend: 1500.0,
    clicks: 2340,
    impressions: 156000,
    conversions: 18,
    ctr: 1.5,
    cpa: 83.33,
    roas: 1.8,
    aiScore: 65,
    aiRecommendation: 'Awareness campaign performing as expected. Monitor view-through conversions.',
  },
  {
    id: 'camp-7',
    name: 'Demand Gen - New Audiences',
    status: 'ENABLED',
    type: 'DEMAND_GEN',
    spend: 890.0,
    clicks: 1200,
    impressions: 45000,
    conversions: 8,
    ctr: 2.67,
    cpa: 111.25,
    roas: 1.2,
    aiScore: 52,
    aiRecommendation: 'Early stage campaign. Allow more data before optimizing.',
  },
  {
    id: 'camp-8',
    name: 'Non-Brand Generic',
    status: 'ENABLED',
    type: 'SEARCH',
    spend: 4500.0,
    clicks: 6200,
    impressions: 98000,
    conversions: 34,
    ctr: 6.33,
    cpa: 132.35,
    roas: 1.1,
    aiScore: 45,
    aiRecommendation: 'CPA above target. Add negative keywords from search terms report.',
  },
];

export const mockAdGroups: AdGroup[] = [
  {
    id: 'ag-1',
    campaignId: 'camp-1',
    name: 'Brand - Exact Match',
    status: 'ENABLED',
    impressions: 70000,
    clicks: 2100,
    conversions: 32,
    spend: 784.0,
    ctr: 3.0,
    cpa: 24.5,
  },
  {
    id: 'ag-2',
    campaignId: 'camp-1',
    name: 'Brand - Phrase Match',
    status: 'ENABLED',
    impressions: 44000,
    clicks: 1320,
    conversions: 13,
    spend: 450.56,
    ctr: 3.0,
    cpa: 34.66,
  },
  {
    id: 'ag-3',
    campaignId: 'camp-2',
    name: 'Competitor A',
    status: 'ENABLED',
    impressions: 44500,
    clicks: 890,
    conversions: 5,
    spend: 1050.0,
    ctr: 2.0,
    cpa: 210.0,
  },
  {
    id: 'ag-4',
    campaignId: 'camp-2',
    name: 'Competitor B',
    status: 'PAUSED',
    impressions: 50000,
    clicks: 1000,
    conversions: 7,
    spend: 1050.0,
    ctr: 2.0,
    cpa: 150.0,
  },
];

export const mockKeywords: Keyword[] = [
  {
    id: 'kw-1',
    adGroupId: 'ag-1',
    text: 'acme brand',
    matchType: 'EXACT',
    status: 'ENABLED',
    clicks: 1200,
    conversions: 22,
    cpa: 21.0,
    qualityScore: 10,
    spend: 462.0,
  },
  {
    id: 'kw-2',
    adGroupId: 'ag-1',
    text: 'acme company',
    matchType: 'EXACT',
    status: 'ENABLED',
    clicks: 900,
    conversions: 10,
    cpa: 32.2,
    qualityScore: 9,
    spend: 322.0,
  },
  {
    id: 'kw-3',
    adGroupId: 'ag-2',
    text: 'acme',
    matchType: 'PHRASE',
    status: 'ENABLED',
    clicks: 1320,
    conversions: 13,
    cpa: 34.66,
    qualityScore: 8,
    spend: 450.56,
  },
];

// Summary stats
export const mockSummaryStats = {
  totalSpend: mockCampaigns.reduce((sum, c) => sum + c.spend, 0),
  totalConversions: mockCampaigns.reduce((sum, c) => sum + c.conversions, 0),
  totalClicks: mockCampaigns.reduce((sum, c) => sum + c.clicks, 0),
  avgCpa:
    mockCampaigns.filter((c) => c.conversions > 0).reduce((sum, c) => sum + c.cpa, 0) /
    mockCampaigns.filter((c) => c.conversions > 0).length,
};
